version: '3.3'
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_tournament_service
    ports:
     - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - ~/datadbs/postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  redis:
    image: redis:6.2.1-alpine
    container_name: redis_tournament_service
    command: '--requirepass ${REDIS_PASSWORD}'
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    networks:
      - webnet
networks:
  webnet:
